import React from "react";
import { useSelector } from "react-redux";

function riskColor(level) {
  if (level === "Critical") return "var(--red-text)";
  if (level === "Major") return "var(--orange-text)";
  if (level === "Minor") return "var(--green-text)";
  return "var(--text-muted)";
}

export default function RiskAssessmentPanel() {
  const { riskAssessment, completeness, duplicateCheck, rootCause, capa, summary, hasContent } = useSelector(
    (s) => s.complaint
  );

  if (!hasContent) {
    return (
      <div className="card risk-panel">
        <div className="card-header">
          <div>
            <h2>AI Risk Assessment</h2>
            <div className="subtitle">Populated automatically once a complaint is logged</div>
          </div>
        </div>
        <div className="empty-risk">No complaint analyzed yet. Use the assistant above to log one.</div>
      </div>
    );
  }

  return (
    <div className="card risk-panel">
      <div className="card-header">
        <div>
          <h2>AI Risk Assessment</h2>
          <div className="subtitle">Reasoning generated by the AI agent — review before finalizing</div>
        </div>
      </div>

      <div className="risk-summary-row">
        <div>
          <div className="risk-score" style={{ color: riskColor(riskAssessment.risk_level) }}>
            {riskAssessment.risk_level || "—"}
          </div>
          <div className="risk-score-sub">Risk score: {riskAssessment.risk_score ?? "—"}/100</div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div className="risk-score-sub">Completeness</div>
          <div className="risk-score" style={{ fontSize: 20 }}>
            {completeness.completeness_score ?? "—"}%
          </div>
        </div>
      </div>
      {riskAssessment.rationale && <p style={{ fontSize: 12.5, color: "var(--text-muted)" }}>{riskAssessment.rationale}</p>}

      {riskAssessment.regulatory_flags?.length > 0 && (
        <div className="ai-block">
          <h4>⚠️ Regulatory Flags</h4>
          {riskAssessment.regulatory_flags.map((f, i) => (
            <span className="flag-chip" key={i}>
              {f}
            </span>
          ))}
        </div>
      )}

      {duplicateCheck.is_possible_duplicate && (
        <div className="ai-block">
          <h4>🔁 Possible Duplicate</h4>
          <span className="dup-chip">Matches complaint(s) #{duplicateCheck.matched_complaint_ids.join(", #")}</span>
          <p>{duplicateCheck.rationale}</p>
        </div>
      )}

      {rootCause.likely_categories?.length > 0 && (
        <div className="ai-block">
          <h4>🔍 Root Cause Recommendation</h4>
          <ul>
            {rootCause.likely_categories.map((c, i) => (
              <li key={i}>{c}</li>
            ))}
          </ul>
          {rootCause.rationale && <p>{rootCause.rationale}</p>}
        </div>
      )}

      {(capa.corrective_actions?.length > 0 || capa.preventive_actions?.length > 0) && (
        <div className="ai-block">
          <h4>🛠️ CAPA Recommendation</h4>
          {capa.corrective_actions?.length > 0 && (
            <>
              <p style={{ fontWeight: 600, color: "var(--text)" }}>Corrective</p>
              <ul>
                {capa.corrective_actions.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </>
          )}
          {capa.preventive_actions?.length > 0 && (
            <>
              <p style={{ fontWeight: 600, color: "var(--text)" }}>Preventive</p>
              <ul>
                {capa.preventive_actions.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </>
          )}
        </div>
      )}

      {summary && (
        <div className="ai-block">
          <h4>📝 Complaint Summary</h4>
          <p style={{ color: "var(--text)" }}>{summary}</p>
        </div>
      )}

      {completeness.missing_fields?.length > 0 && (
        <div className="ai-block">
          <h4>✅ Completeness Checker</h4>
          <p>Missing: {completeness.missing_fields.join(", ")}</p>
        </div>
      )}
    </div>
  );
}
